services:
  postgres:
    image: postgres:17.2
    container_name: ${DB_NAME}
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - data_db:/var/lib/postgresql/data
    networks:
      - network_db

volumes:
  data_db:

networks:
  network_db:
    driver: bridge